
# Directory Structure

root_dir: '/Tree-Mortality/data'
projections_subdir: 'projections/BCM'
mortality_subdir: 'tree_mortality'
bcm_subdir: 'bcm'
topo_subdir: 'topo'
bcm_raw_subdir: 'BCMv8_zip'
results_subdir: 'results'
figures_subdir: 'figures'

# Script Configuration Files

bcm_config: 'config/bcm_v8.json'
agg_config: 'config/bcm_v8_aggregation.json'
bcm_ind_config: 'config/bcm_v8_indices.json'
bcm_proj_ind_config: 'config/bcm_v8_proj_indices.json'
mort_config: 'config/tree_mortality.json'
mort_fold_config: 'config/tree_mortality_folds.json'
mort_rand_fold_config: 'config/tree_mortality_rand_folds.json'
mort_trainset_config: 'config/training_features.json'
topo_config: 'config/topo_variables.json'

bcm_variables:
#    - aet
#    - cwd
#    - pck
    - pet
    - ppt
#    - rch
#    - run
#    - str
#    - tmn
#    - tmx

# Climate Projections

projection_scenarios: 'RCP45'
    #- HST
#    -
#    - RCP85

projection_models: 'GFDL-CM3'
#    - ACCESS1-0
#    - CCSM4
#    - CESM1-BGC
#    - CMCC-CMS
#    - CNRM-CM5
#    - CanESM2
#    -
#    - HadGEM2-ES
#    - MIROC5

# Topography
topobase: 'SRTM_SierraConservancy_3310_.tif'
